version: '3'
services:
  db:
    build: 
      context: ./
      dockerfile: ./build/db/Dockerfile
    container_name: dockerMySQL 
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdatabase
      MYSQL_USER: testuser
      MYSQL_PASSWORD: password
    ports: 
      - "3306:3306"
    
    volumes:
     - ./build/db/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: 
      context: ./
      dockerfile: ./build/app/Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
